name: CI/CD with GitHub Container Registry (GHCR)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Authenticate to GHCR
      - name: Authenticate to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ghcr.io/nethmipathirana/doctor-information-ms:latest .

      # Step 6: Push Docker Image to GHCR
      - name: Push Docker Image
        run: docker push ghcr.io/nethmipathirana/doctor-information-ms:latest

      # Step 7: Verify Image Content
      - name: Verify Image Content
        run: docker run --entrypoint ls ghcr.io/nethmipathirana/doctor-information-ms:latest /app
